pipeline{
    agent any
    
    stages{
        stage('build'){
            steps{
                sh 'echo Build'
                }
            }
	stage('test'){
            steps{
                sh 'echo Test'
                }
	    }

	stage('deeploy'){

            steps{
                sh 'echo Deploy'
                }
            }

        }
    }
